### PR TITLE
[Feature] Fix referencing of Cecil pre-release package

### LINKED ISSUE #70: Can't update to 2.3.0 via NuGet
Error is "Unable to find a version of 'Mono.Cecil' that is compatible with 'Machine.Specifications.Runner.VisualStudio 2.3.0 constraint: Mono.Cecil (>= 0.10.0-beta6)'."

2.4.0 has the same issue.

My target is .NET Framework 4.7 x64

### PR DESCRIPTION
**Pull request by robertcoltheart**
Fixes #70 

I've taken the inspiration for this from the nunit adapter here: https://github.com/nunit/nunit3-vs-adapter/blob/master/src/NUnitTestAdapter/NavigationDataProvider.cs

Would appreciate someone going over it to validate, as I'm not super familiar with Cecil.

### CODE REVIEW

File: Source/Machine.VSTestAdapter/Discovery/BuiltIn/SourceCodeLocationFinder.cs [hunk 1]
```diff
@@ -90,6 +94,17 @@ private SourceCodeLocationInfo GetFieldLocationCore(TypeDefinition type, string
 
             return null;
         }
+
+        private bool IsHidden(SequencePoint sequencePoint)
+        {
+            const int lineNumberIndicatingHiddenLine = 16707566;
```
Comment (ivanz) [inline Source/Machine.VSTestAdapter/Discovery/BuiltIn/SourceCodeLocationFinder.cs]: Minor suggestion to encode this value as `0xFEEFEE` which slightly more google-ble  👍
